'use client';
import React from 'react';
function Container({ children }: { children: React.ReactNode }) { return <div className="mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8">{children}</div>; }
export default function PlanReadingLanding(){ return (<div className="min-h-screen bg-neutral-50 text-neutral-900"><TopNav/><Hero/><CTA/><Footer/></div>); }
function TopNav(){ return (<header className="sticky top-0 z-40 backdrop-blur bg-white/80 border-b border-neutral-200"><Container><div className="flex h-16 items-center justify-between">
<div className="flex items-center gap-3"><span className="inline-flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-600 text-white font-bold">PR</span><div><div className="text-lg font-semibold">PlanReading Academy</div><div className="text-xs text-neutral-500">Learn to read construction plans with confidence</div></div></div>
<nav className="hidden md:flex items-center gap-6 text-sm"><a href="/courses/plan-reading" className="hover:text-emerald-700">Lessons</a><a href="/sign-in" className="hover:text-emerald-700">Sign in</a></nav>
<div className="flex items-center gap-3"><a href="#pricing" className="hidden sm:inline-flex px-4 py-2 rounded-xl border border-neutral-300 hover:border-neutral-400">View plans</a><a href="#pricing" className="inline-flex px-4 py-2 rounded-xl bg-emerald-600 text-white hover:bg-emerald-700">Enroll</a></div></div></Container></header>); }
function Hero(){ return (<section className="relative overflow-hidden"><div className="absolute inset-0 -z-10 bg-gradient-to-b from-emerald-50 to-white"/><Container><div className="grid lg:grid-cols-2 gap-10 py-16 lg:py-24 items-center"><div>
<h1 className="text-4xl md:text-5xl font-extrabold tracking-tight leading-tight">Master construction plan reading — from title block to takeoff.</h1>
<p className="mt-5 text-lg text-neutral-700">Practical, job-ready training for estimators, PMs, apprentices, and tradespeople.</p>
<div className="mt-6 flex flex-wrap gap-3"><a href="/courses/plan-reading" className="px-5 py-3 rounded-xl bg-emerald-600 text-white hover:bg-emerald-700">See Lessons</a><a href="#pricing" className="px-5 py-3 rounded-xl border border-neutral-300 hover:border-neutral-400">Pricing</a></div>
</div><div className="relative"><img src="/images/blueprints-desk.svg" alt="Estimator reviewing architectural plans" className="w-full rounded-2xl shadow-xl ring-1 ring-black/5"/></div></div></Container></section>); }
function CTA(){ return (<section className="py-12"><Container><div className="rounded-2xl bg-emerald-600 text-white p-8 md:p-10 flex flex-col md:flex-row items-center justify-between gap-6"><div><h3 className="text-2xl font-extrabold">Ready to read plans with confidence?</h3><p className="mt-1 text-emerald-100">Enroll now and start Lesson 1 in minutes.</p></div><a href="#pricing" className="inline-flex px-6 py-3 rounded-xl bg-white text-emerald-700 font-medium hover:bg-emerald-50">Enroll</a></div></Container></section>); }
function Footer(){ return (<footer className="py-10 border-t border-neutral-200 bg-white"><Container><div className="grid md:grid-cols-3 gap-6 items-center"><div className="text-sm text-neutral-600">© {new Date().getFullYear()} PlanReading Academy.</div><div className="text-sm text-neutral-600 flex gap-4 justify-center"><a href="#" className="hover:underline">Terms</a><a href="#" className="hover:underline">Privacy</a><a href="#" className="hover:underline">Refunds</a></div><div className="flex md:justify-end gap-3"><a href="/courses/plan-reading" className="px-4 py-2 rounded-xl border border-neutral-300 hover:border-neutral-400 text-sm">Lessons</a><a href="/sign-in" className="px-4 py-2 rounded-xl bg-emerald-600 text-white hover:bg-emerald-700 text-sm">Sign in</a></div></div></Container></footer>); }
